name: C++
on:
  workflow_call:
    inputs:
      cpp_std_version:
        required: true
        type: string
      build_type:
        required: false
        type: string
        default: "Debug"

jobs:
  linux-x64-gcc:
    name: Linux x64 (GCC)
    uses: cach30verfl0w/aetherium/.github/workflows/gcc.yml@develop
    with:
      job_name: Linux x64 (GCC)
      image_name: ubuntu-22.04
      cpp_std_version: ${{inputs.cpp_std_version}}
      gcc_version: 12
      build_type: ${{inputs.build_type}}
  linux-x64-clang:
    name: Linux x64 (Clang)
    uses: cach30verfl0w/aetherium/.github/workflows/gcc.yml@develop
    with:
      job_name: Linux x64 (Clang)
      image_name: ubuntu-22.04
      cpp_std_version: ${{inputs.cpp_std_version}}
      clang_version: 15
      build_type: ${{inputs.build_type}}