name: Build and Test
on:
  push:

jobs:
  cpp-17-debug:
    name: C++ 17 (Debug)
    uses: cach30verfl0w/aetherium/.github/workflows/cpp.yml@develop
    with:
      cpp_std_version: 17
  cpp-20-debug:
    name: C++ 20 (Debug)
    uses: cach30verfl0w/aetherium/.github/workflows/cpp.yml@develop
    with:
      cpp_std_version: 20